// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN_tpeO7dlNPBAj_lJS_yZoL3eNaRSzRc',
    appId: '1:241519834553:web:390a160b1ffbc9acacb268',
    messagingSenderId: '241519834553',
    projectId: 'authentication-5c368',
    authDomain: 'authentication-5c368.firebaseapp.com',
    databaseURL: 'https://authentication-5c368-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-5c368.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSJ4VaohBaVLGbLg-0IpNvahCLlbpXXVw',
    appId: '1:241519834553:android:e510b60dbdb4f544acb268',
    messagingSenderId: '241519834553',
    projectId: 'authentication-5c368',
    databaseURL: 'https://authentication-5c368-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-5c368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFkfP-AixdCfN9j8ndTCX21KqV7ZMuV-I',
    appId: '1:241519834553:ios:8481cdab454a858aacb268',
    messagingSenderId: '241519834553',
    projectId: 'authentication-5c368',
    databaseURL: 'https://authentication-5c368-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-5c368.appspot.com',
    iosClientId: '241519834553-nth5au210ifnel3q0fsd58spk6jlv52f.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospitalManagementSystem',
  );
}
